autumn = Season.create(name: 'Autumn')
winter = Season.create(name: 'Winter')
spring = Season.create(name: 'Spring')
summer = Season.create(name: 'Summer')


Activity.create(name: "Skiing", location: "Upstate New York", price: 200.00, season: winter)
Activity.create(name: "Snowboarding", location: "Adirondack", price: 300.00, season: winter)
Activity.create(name: "Ice Fishing", location: "Connecticut", price: 70.00, season: winter)
Activity.create(name: "Dog Sledding", location: "Alaska", price: 450.00, season: winter)
Activity.create(name: "SnowMobiling", location: "Upstate New York", price: 250.00, season: winter)
Activity.create(name: "Tubing", location: "Upstate New York", price: 100.00, season: winter)

Activity.create(name: "Picnics", location: "Central Park", price: 2.00, season: spring)
Activity.create(name: "Gardening", location: "Your Home", price: 30.00, season: spring)
Activity.create(name: "Cleaning", location: "Your Home", price: 10.00, season: spring)
Activity.create(name: "Hiking", location: "Upstate New York", price: 5.00, season: spring)
Activity.create(name: "Baseball", location: "MLB Statium", price: 120.00, season: spring)

Activity.create(name: "Apple Picking", location: "Upstate New York", price: 50.00, season: autumn)
Activity.create(name: "Pumpkin Picking", location: "Local Farm", price: 30.00, season: autumn)
Activity.create(name: "Trick-or-treating", location: "Your Hometown", price: 1.00, season: autumn)
Activity.create(name: "Pie baking", location: "Your Hometown", price: 30.00, season: autumn)
Activity.create(name: "Corn mazes", location: "Upstate New York", price: 20.00, season: autumn)
Activity.create(name: "Hiking", location: "Adirondack", price: 5.00, season: autumn)
Activity.create(name: "Tailgating", location: "Football Statiums", price: 20.00, season: autumn)

Activity.create(name: "Swimming", location: "Local Pool", price: 10.00, season: summer)
Activity.create(name: "Barbeques", location: "Your Backyard", price: 40.00, season: summer)
Activity.create(name: "Camping", location: "Upstate New York", price: 60.00, season: summer)
Activity.create(name: "Beach-going", location: "Jones Beach", price: 15.00, season: summer)
Activity.create(name: "Fishing", location: "Upstate New York", price: 10.00, season: summer)
Activity.create(name: "County fairs", location: "Your Community", price: 30.00, season: summer)
Activity.create(name: "Street festivals", location: "Your Community", price: 50.00, season: summer)
